image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache --update python3 python3-dev py3-pip
  - pip install awscli --upgrade
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

build:
  stage: build
  script:
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"

#deploy:
#  stage: deploy
#  services:
#    - docker:dind
#  script:
#    - aws ecs update-service --cluster hazeron-discord-bot --service hazeron-discord-bot-service --region us-west-2 --force-new-deployment
